### ISSUE TITLE
Error occured when data processing

### ISSUE THREAD

**Issue by lajictw** [THUNLP-MT/PS-VAE#11]
Dear authors,

Hi! When running train.py, at the data-processing stage, an error occured. When train.py at line 26 called _self.data = torch.load(self.save_path)_, it get into the file _bpe_dataset.py_ properly. But at line 26, an error occured saying _No such file or directory_ for the file processed_data.pkl. As there is a try-catch structure, it runs line 28, _self.data = self.process()_. But when running line 28, another error occurs, saying 

> Boost.Python.ArgumentError: Python argument types in
>     rdkit.Chem.rdmolops.RemoveStereochemistry(NoneType)
> did not match C++ signature:
>     RemoveStereochemistry(class RDKit::ROMol {lvalue} mol)

for the file chem_utils.py at line 69. Can you tell me how to fix these errors or how to avoid them? Thanks!

**Comment by kxz18** [comment]
Hi, can you check the smiles that caused the error? The errors imply that RDKit failed to parse the given smiles into a molecule object at [line 68 in chem_utils.py](https://github.com/THUNLP-MT/PS-VAE/blob/6881b1ea4e7605abd6f5be2fce96f07f65332290/src/utils/chem_utils.py#L68C1-L69C1), which means the provided smiles might be valid.

**Comment by lajictw** [comment]
So you are inferring that the problem may be illegitimate SMILES inputs. But due to the shuffling, the number of iterations is different for each stop. How should I check which SMILES input is causing this problem? Is it possible that the position where the iteration stops after I deactivate the shuffle is the position where the input error occurs? And I am training on the qm9 dataset you provided. I am not inclined to think that the dataset you provided has the potential for error.

**Comment by kxz18** [comment]
The error occurs during the [preprocessing phase](https://github.com/THUNLP-MT/PS-VAE/blob/6881b1ea4e7605abd6f5be2fce96f07f65332290/src/data/bpe_dataset.py#L165), where there is no shuffling. Therefore, the position that the iteration stops should be exactly the line of the smiles that caused the trouble. For me on this case, I would first track down the position that the iteration stops (suppose the position is *i*). Then revise [the code](https://github.com/THUNLP-MT/PS-VAE/blob/6881b1ea4e7605abd6f5be2fce96f07f65332290/src/data/bpe_dataset.py#L165) as follows:

```python
for s in tqdm(smiles[i-1:]):
    print(s)
    mol = chem_utils.smiles2molecule(s, kekulize=True)
    data_list.append(self.process_step1(mol, self.tokenizer))
```

In this way, you should directly see the smiles that caused the trouble. Then you can validate my hypothesis by running the following codes in python:

```python
from rdkit import Chem

s = 'the one that caused the trouble'
mol = Chem.MolFromSmiles(s)
assert mol is not None
```

**Comment by lajictw** [comment]
Thanks for your help. I successfully located the smiles that caused the error. The screenshot is attached below. But how can I fix that?

![image](https://github.com/THUNLP-MT/PS-VAE/assets/40271784/91e2ab50-ddee-4a79-8776-f09ff12ecfb1)
![image](https://github.com/THUNLP-MT/PS-VAE/assets/40271784/4bd3981e-50d2-4110-a4cb-c368cf25fa5e)
![image](https://github.com/THUNLP-MT/PS-VAE/assets/40271784/8c67b18a-cd22-46db-b627-a1bf62cc1ac9)

**Comment by kxz18** [comment]
Hi, I've added some codes to skip the smiles that cannot be handled by rdkit (see [here](https://github.com/THUNLP-MT/PS-VAE/blob/9369aa1abe838ceabdd9906cf13e32db6c2a5c35/src/data/bpe_dataset.py#L167) and [here](https://github.com/THUNLP-MT/PS-VAE/blob/9369aa1abe838ceabdd9906cf13e32db6c2a5c35/src/utils/chem_utils.py#L69)). Now it should work.

**Comment by lajictw** [comment]
Thanks for your help! Code works for the data loading part
