### ISSUE TITLE
Some questions about the token

### ISSUE THREAD

**Issue by windyLemon** [THUNLP-MT/PS-VAE#3]
Dear author, i run the file mol_bpe.py and generate the vocab of zinc250. However, i notice the vocab exists the same fragment.  Is this correct？

**Comment by kxz18** [comment]
Oh, we didn't observe this phenomenon during our experiments. Could you please provide the command to run mol_bpe.py as well as the information of the repeated entries so that we may dig into it?

**Comment by windyLemon** [comment]
Thanks for your reply! I run the command in readme. for example the previous issue https://github.com/THUNLP-MT/PS-VAE/issues/1#issuecomment-1293385149 vocab 

c1ccncc1	6	5950
c1cncnc1	6	9161
c1ccncc1	6	5950

c1ccncc1 appears twice.  I generate the vocab of zinc250 and also notice this fragment appear twice. Since i am a beginner of this area, i do not know if it is right. Hope for your reply.

**Comment by kxz18** [comment]
This is kind of weired, though it may not interfere with later usage of the vocabulary. I'm looking into it.

**Comment by kxz18** [comment]
I found that this is because the subgraph is again merged from another path, which is a corner case. I've fixed this corner case in the new commit 635e6d1aaaec01619314f43327cac50f965051a5. Thank you for notifiying of this phenomenon!

**Comment by windyLemon** [comment]
Thanks! I will try it!
