### ISSUE TITLE
gpu acclerator in pytorch_lightning

### ISSUE THREAD

**Issue by yangzhao1230** [THUNLP-MT/PS-VAE#5]
Hi,

Thanks for you work. When I ran the code, it seemed that no gpu was used to acclerate, following your default config. I am unfamiliar with pytorch_lightning, but i find add a line of code as follows works:
![image](https://user-images.githubusercontent.com/52462696/221402156-e28034f6-3561-4ace-9cec-31814110d5b0.png)

I want to know why I met this problem. Thank you.

**Comment by kxz18** [comment]
Is it because you are using the latest version of pytorch_lightning?  It looks like the latest version needs to explicitly add the 'accelerator' parameter in the config: https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.trainer.trainer.Trainer.html

**Comment by yangzhao1230** [comment]
It does seem to be like that. Thanks a lot!
