### ISSUE TITLE
version of Tensorflow

### ISSUE THREAD

**Issue by yangzhao1230** [THUNLP-MT/PS-VAE#6]
Can you provide me with the versions of your TensorFlow, Keras, and Guacamol? I encountered an error while conducting FCD testing, which seems to be related to TensorFlow. As I am not familiar with TensorFlow, I need your help. Thank you!

**Comment by yangzhao1230** [comment]
screenshot:
![image](https://user-images.githubusercontent.com/52462696/223043024-9613f814-f98d-449e-8002-61cb3bfe8515.png)

**Comment by kxz18** [comment]
My versions are as follows:
guacamol==0.5.4
keras==2.10.0
tensorflow==2.10.0

I also struggled to install the Guacamol suite. It may help to refer to [their official github](https://github.com/BenevolentAI/guacamol) if the above versions cannot solve your problem.
