### ISSUE TITLE
Number of motifs (N) for distribution learning

### ISSUE THREAD

**Issue by byeongkeunahn** [THUNLP-MT/PS-VAE#7]
Hi, thanks for the great work!
I've read from the paper that N=300 was used for property optimization and N=500 for constrained property optimization.
However, I could not find the same information for the distribution learning benchmark (Table 1).
I've also taken a look at the repository, but it was unclear for me which values of N were used.
Would you mind sharing the values of N for the distribution learning benchmark on QM9 and ZINC250K, respectively?
Thanks in advance!

**Comment by kxz18** [comment]
Hi, for distribution learning benchmark on QM9 and ZINC250K, we set N=101 and N=500, respectively. The checkpoints and vocabularies are also available on [Google Drive](https://drive.google.com/drive/folders/1FeKZFJAM-mS_Rj4LD9biMTxKLmSVsG2V).

**Comment by byeongkeunahn** [comment]
Thanks for the answer!
